name: Sync from template
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Update scikit-learn PRs
        run: python build_tools/generate_scikit-learn_prs.py

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update dynamic information
          body: |
            - Update scikit-learn PRs
          branch: update-dynamic-info
